# Main composition file for serial upgrade container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:

  # TFTP server service:
  tftpserver:
    container_name: tftpserver
    ports:
      - "69:69/udp"
    volumes:
      - "./data:/tftpshare"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-TFTP
    restart: always

  # Ping container to 192.168.0.1
  ping-container:
    container_name: ping-container
    image: alpine
    command: sh -c "while true; do ping -c 4 192.168.0.1; sleep 1; done"
    restart: always
    network_mode: host   # Isso garante que o contêiner use a rede do host

volumes:
  ssh-keys:
