# Main composition file for serial upgrade container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:

  # TFTP server service:
  tftpserver:
    container_name: tftpserver
    ports:
      - "69:69/udp"
    volumes:
      - "./data:/tftpshare"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-TFTP
    restart: always

  # Ping container to 192.168.0.1
  ping-container:
    container_name: ping-container
    image: alpine
    command: sh -c "while true; do if ping -c 4 192.168.0.1 > /dev/null 2>&1; then echo 'Finalizado'; else echo 'Atualizando...'; fi; sleep 1; done"
    restart: always
    network_mode: host 

volumes:
  ssh-keys:
