# Main composition file for FTP Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:

  # FTP server service:
  ftpserver:
    container_name: ftpserver
    ports:
      - '21:21' # FTP Control Connection Ports
      - '65000-65004:65000-65004' # FTP Transfer ports
    volumes:
       - "./data/:/data/infraremp"
       - "./log:/var/log/"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-FTP
    env_file:
      - ./env/.env_ftp
    restart: always

  # TFTP server service:
  tftpserver:
    container_name: tftpserver
    ports:
      - "514:514/udp"
    volumes:
      - "./data:/tftpshare"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-TFTP
    network_mode: "host"
    restart: always