# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

# Use the base image for FTP:
FROM arthurcadore/vsftp-fh:1.0
    
# Starts and Mantain container running:
CMD ["/start-ftp"]
  